### ISSUE TITLE
Uh oh! Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by happysahota** [JimmyBoh/pully#26]
I created index.ts file and executed it as "ts-node index.ts" and it downloaded the file but at the last moment of conversion to mp3 which need ffmpeg it pissed :-1: 
----------------------------
Progress: 98.32%
Uh oh! Error: Cannot find ffmpeg
    at C:\singletonCode\ytdl\node_modules\fluent-ffmpeg\lib\processor.js:136:22
    at C:\singletonCode\ytdl\node_modules\fluent-ffmpeg\lib\capabilities.js:123:9
    at C:\singletonCode\ytdl\node_modules\async\dist\async.js:473:16
    at next (C:\singletonCode\ytdl\node_modules\async\dist\async.js:5329:29)
    at C:\singletonCode\ytdl\node_modules\async\dist\async.js:969:16
    at C:\singletonCode\ytdl\node_modules\fluent-ffmpeg\lib\capabilities.js:116:11
    at C:\singletonCode\ytdl\node_modules\fluent-ffmpeg\lib\utils.js:223:16
    at F (C:\singletonCode\ytdl\node_modules\which\which.js:68:16)
    at E (C:\singletonCode\ytdl\node_modules\which\which.js:80:29)
    at C:\singletonCode\ytdl\node_modules\which\which.js:89:16
Progress: 100%

**Comment by happysahota** [comment]
I assume I'm executing this in wrong manner so looking forward for the correct way to get it done.

**Comment by happysahota** [comment]
hmmm finally resolved it by setting system variable:  FFMPEG_PATH
