### ISSUE TITLE
cli crashes in node-progress

### ISSUE THREAD

**Issue by clux** [JimmyBoh/pully#5]
Tried `pully https://www.youtube.com/watch?v=gEdc27Iz8zA`
And a variety of others to make sure, but they all crash with this output atm:

```
/home/clux/local/node-v5.1.0/lib/node_modules/pully/node_modules/progress/lib/node-progress.js:131
  complete = Array(completeLength + 1).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (/home/clux/local/node-v5.1.0/lib/node_modules/pully/node_modules/progress/lib/node-progress.js:131:14)
    at ProgressBar.tick (/home/clux/local/node-v5.1.0/lib/node_modules/pully/node_modules/progress/lib/node-progress.js:86:8)
    at PassThrough.<anonymous> (/home/clux/local/node-v5.1.0/lib/node_modules/pully/lib/downloader.js:142:15)
    at emitOne (events.js:82:20)
    at PassThrough.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at PassThrough.Readable.push (_stream_readable.js:110:10)
    at PassThrough.Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:76:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)
```

node@5.1.0 and npm@3.5.0

**Comment by JimmyBoh** [comment]
Hmmm, thanks @clux. I'll try to reproduce this in a few hours. If it is an issue with `node-progress` then either I can create an issue for them or you can, but I'll let you know after I mess around a bit.

**Comment by tusharmath** [comment]
Yeah. Makes the module unusable :(

**Comment by alexbinary** [comment]
Hi,
I investigated the problem and here are my conclusions :

crash occurs at https://github.com/tj/node-progress/blob/1.1.8/lib/node-progress.js#L131
-> [node-progress] because `completeLength` is `NaN`.
-> [node-progress] because `ratio` is `NaN` (https://github.com/tj/node-progress/blob/1.1.8/lib/node-progress.js#L109)
-> [node-progress] because `this.total` is `NaN`
-> [node-progress] because `options.total` is `Nan` (https://github.com/tj/node-progress/blob/1.1.8/lib/node-progress.js#L56)
=> [pully] because `streamFormat.size` is `undefined` (https://github.com/JimmyBoh/pully/blob/master/lib/downloader.js#L110, even before it goes into `parseInt`)

**Comment by JimmyBoh** [comment]
Nice triage, I appreciate the help. You also found an [incorrect usage of `parseInt`](https://github.com/JimmyBoh/pully/blob/master/lib/downloader.js#L110).

I'm sorry I haven't had time to fully address this. I will be sure to test it today, hopefully with a fix up on NPM by tonight (EST).

**Comment by JimmyBoh** [comment]
A big apology for the delay. A new build is up now that fixes this issue.

**Comment by JimmyBoh** [comment]
And a few other updates, ES2015 features mostly.
